# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'

- task: UiPathInstallPlatform@2
  displayName: 'UiPath Install Platform CLI...'


- task: UiPathPack@2
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)\HelloWorld\project.json'
    orchestratorConnection: 'TAM Demo - DEV'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
    traceLevel: 'Verbose'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'paf_HelloWorld'
    publishLocation: 'Container'

- task: UiPathDeploy@2
  inputs:
    orchestratorConnection: 'TAM Demo - DEV'
    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
    folderName: 'Demo'
    entryPoints: 'HelloWorld.xaml'
    traceLevel: 'Information'