# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest


jobs:
- job: BuildPackages
  steps:
    - task: UiPathPack@2
      displayName: Run Workflow Analysis and Pack sourcecode
      inputs:
        versionType: 'AutoVersion'
        projectJsonPath: '$(Build.SourcesDirectory)\HelloWorld\project.json'
        orchestratorConnection: 'TAM Demo - DEV'
        outputPath: '$(Build.ArtifactStagingDirectory)\Output'
        runWorkflowAnalysis: true
        traceLevel: 'Verbose'
  
- job: PubishArtifacts
  dependsOn: BuildPackages
  steps:
    - task: PublishPipelineArtifact@1
      displayName: Publish asset csv file
      inputs:
        targetPath: '$(Build.SourcesDirectory)\HelloWorld\sampleAsset.csv'
        artifact: 'af_asset' 
        publishLocation: 'pipeline'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'af_HelloWorld'
        publishLocation: 'Container'

- job: DeployToDevelopment
  dependsOn: PubishArtifacts
  steps:
    - task: UiPathDeploy@2
      inputs:
        orchestratorConnection: 'TAM Demo - DEV'
        packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
        folderName: 'Demo'
        entryPoints: 'HelloWorld.xaml'
        traceLevel: 'Information'

    - task: UiPathAssets@2
      displayName: Deploy assets into Development tenant
      inputs:
        orchestratorConnection: 'TAM Demo - DEV'
        folderName: 'Demo'
        assetActionType: 'Deploy'
        csvFile: '$(Build.SourcesDirectory)\HelloWorld\sampleAsset.csv'








