# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev

pool:
  vmImage: windows-latest


jobs:
- job: BuildAndDeployPackage
  steps:
    - task: UiPathPack@2
      displayName: Run Workflow Analysis and Pack Sourcecode
      inputs:
        versionType: 'AutoVersion'
        projectJsonPath: '$(Build.SourcesDirectory)\HelloWorld' # can add \project.json here
        orchestratorConnection: 'TAM Demo - DEV'
        outputPath: '$(Build.ArtifactStagingDirectory)'
        outputType: 'None'
        runWorkflowAnalysis: true
        traceLevel: 'Information'
    - task: PublishPipelineArtifact@1
      displayName: Publish nuget pack from previous build
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'af_HelloWorld'
        publishLocation: 'pipeline'     

    - task: UiPathDeploy@2
      displayName: Deploy nuget package to Development
      inputs:
        orchestratorConnection: 'TAM Demo - DEV'
        packagesPath: '$(Build.ArtifactStagingDirectory)'
        folderName: 'Demo'
        entryPoints: 'HelloWorld.xaml'
        traceLevel: 'Information' 
  
- job: PubishAndDeployAsset
  #dependsOn: BuildPackages
  steps:
    - task: PublishPipelineArtifact@1
      displayName: Publish asset csv file
      inputs:
        targetPath: '$(Build.SourcesDirectory)\HelloWorld\Config\sampleAsset.csv'
        artifact: 'af_asset' 
        publishLocation: 'pipeline'
    - task: UiPathAssets@2
      displayName: Deploy assets to Development
      inputs:
        orchestratorConnection: 'TAM Demo - DEV'
        folderName: 'Demo'
        assetActionType: 'Deploy'
        csvFile: '$(Build.SourcesDirectory)\HelloWorld\Config\sampleAsset.csv'













